### ISSUE TITLE
Make app "invisible"

### ISSUE THREAD

**Issue by 7k50** [Gaulomatic/AirPodsSanity#1]
Hey, this is exactly what I was looking for!

However, I find it very annoying (unfortunately) that the app creates a window that visibly takes up space on MacOS (Mission Control, app management, etc) seeing at it doesn't do anything other than say "Keep your sanity in check!".

Can we please have the app instead be entirely "invisible" except existing as either a Menu Bar app, or a Dock app with no "window" attached?

**Comment by Gaulomatic** [comment]
Hey, thanks for the feedback. This one was on my list as well, so I updated the code and released version 1.0.3. You can download the code or use the pre-compiled version as DMG.

**Comment by 7k50** [comment]
> Hey, thanks for the feedback. This one was on my list as well, so I updated the code and released version 1.0.3. You can download the code or use the pre-compiled version as DMG.

Wonderful. Thanks so much!
