### ISSUE TITLE
Application can’t be opened because Apple cannot check it for malicious software

### ISSUE THREAD

**Issue by mwisnicki** [Gaulomatic/AirPodsSanity#13]
Great app but the installation instructions should probably mention you have to do

```
xattr -d com.apple.quarantine "/Applications/AirPods Sanity.app"
```

**Comment by Gaulomatic** [comment]
Good idea, fixed in https://github.com/Gaulomatic/AirPodsSanity/commit/b7a645f54f1f4979cca31d38aaaf9fad6750eb09
