### ISSUE TITLE
Launch at Login

### ISSUE THREAD

**Issue by raisedadead** [Gaulomatic/AirPodsSanity#3]
A quick option for "launch at login" would be really nice. The current workaround is to manually add the app in the Login items in the System settings.

Thanks for building this.

**Comment by habovh** [comment]
@Gaulomatic, @raisedadead this has been addressed on [milgra/airpodssoundqualityfixer](https://github.com/milgra/airpodssoundqualityfixer).

**Comment by Gaulomatic** [comment]
This feature has been implemented in 1.0.4. Thanks for the suggestion.
