### ISSUE TITLE
Thank you for making this

### ISSUE THREAD

**Issue by yougotwill** [Gaulomatic/AirPodsSanity#5]
My mental health has improved by 200% since installing this. You are a legend 😎 

Feel free to delete but just wanted to say thanks!

**Comment by tophermetcalfe** [comment]
Agreed! I wish there were a thank you button!  I can't believe that you needed to make this, but I'm so so so happy you did.

**Comment by SoCuul** [comment]
> My mental health has improved by 200% since installing this. You are a legend 😎
> 
> Feel free to delete but just wanted to say thanks!

I'd recommend marking this as a closed issue (for the repository stats).

I want to say thank you as well though for this app!

**Comment by Gaulomatic** [comment]
Thanks all for the thanks 😀
